
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Azhu-SectionSearchBug","number":57,"title":"Azhu - add Is Section? column","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/57"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-projCourse-Finals1","number":56,"title":"BC - Make finals information available, Part 1","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/56"},{"author":{"id":"U_kgDOBXhX9g","is_bot":false,"login":"apzhou0","name":""},"headRefName":"Audrey-quarter","number":46,"title":"azhou - Course Details Button","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/46"},{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-AddCourseStatus","number":45,"title":"Added section status to table","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/45"},{"author":{"id":"MDQ6VXNlcjc2NDUzODIw","is_bot":false,"login":"EricM5","name":"Eric Marzouk"},"headRefName":"em-addgithubtosysteminfo","number":44,"title":"EricM5 - Add Github info to /api/SystemInfo endpoint and display on Developer Page","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/44"}]
