
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-4
pull_requests: [{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"anisavic-patch-1","number":76,"title":"Update README.md","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/76"},{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-HistoricGrades","number":75,"title":"WIP - placeholder for historic grade data","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/75"},{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Azhu-SectionNumberColumn","number":74,"title":"Azhu - Add New Section Number Column","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/74"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-UpdateDokku","number":73,"title":"BC - Deployed dokku and updated README","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/73"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-ProjCourses-FinalPart2","number":67,"title":"BC - Added the endpoint for finalsInfo","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/67"},{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"Sasha-Better-Job-Logs-Part1","number":64,"title":"Sasha - EPIC for better job logs, Part 1","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/64"},{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"Sasha-Feature-Form-To-Create-1","number":60,"title":"Sasha-FEATURE: Form to create PS course has drop down for Course Schedules","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/60"},{"author":{"id":"MDQ6VXNlcjc2NDUzODIw","is_bot":false,"login":"EricM5","name":"Eric Marzouk"},"headRefName":"em-addgithubtosysteminfo","number":44,"title":"EricM5 - Add Github info to /api/SystemInfo endpoint and display on Developer Page","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/44"}]
